#!/bin/sh
# Weekday backup (five cycling backups)
set -e +a +m +s +i -f

local day="$(/usr/local/bin/date +%a)"
local backupdir="$VAR_BACKUP_DIR/weekdays/$day"
local IFS=$(echo -en "\n\b,")
local schemas=""
local tables=""
local dumpCmd=""
local blobs=""
local clean=""
local format=""
local jobs=""
for database in $VAR_DATABASES
do
   dumpCmd="/usr/local/bin/pg_dump --host=$VAR_HOST --port=$VAR_PORT --username=$VAR_LINUX_USER --dbname=$database"
   eval "format=\$VAR_$database_format"
   if [ -z "$format" ]
   then
      format=$VAR_FORMAT
   fi
   dumpCmd="$dumpCmd --format=$format"
   if [ "$format" == "directory" ]
   then
      eval "jobs=\$VAR_$database_jobs"
      if [ -z "$jobs" ]
      then
         jobs=$VAR_JOBS
      fi
      dumpCmd="$dumpCmd --jobs=$jobs"
   fi
   eval "clean=\$VAR_$database_clean"
   if [ "$clean" != "no" ]
   then
      if [ "$clean" == "yes" ] || [ "$VAR_CLEAN" == "yes" ]
      then
         dumpCmd="$dumpCmd --clean"
      fi
   fi
   eval "xschemas=\$VAR_$database_excludeschemas"
   for xschema in $xschemas
   do
      dumpCmd="$dumpCmd --exclude-schema=$xschema"
   done
   eval "schemas=\$VAR_$database_schemas"
   for schema in $schemas
   do
      dumpCmd="$dumpCmd --schema=$schema"
      eval "xtables=\$VAR_$database_$schema_excludetables"
      for xtable in $xtables
      do
         dumpCmd="$dumpCmd --exclude-table=$xtable"
      done
      eval "tables=\$VAR_$database_$schema_tables"
      for table in $tables
      do
         dumpCmd="$dumpCmd --table=$table"
      done
            /usr/local/bin/pg_dump -U $VAR_LINUX_USER -p $VAR_PORT -N 'public' -N '*_' --exclude-table-data='*.*_' -Z 9 $i > "$BACKUPDIR/$i.sql.gz"
   pg_dump -U postgres -p 5432 -c -t 'layer_styles' -Z 9 $i > "$BACKUPDIR/$i-layer_styles.sql.gz"
done
pg_dumpall -h localhost -p 5432 -U postgres -w -v --globals-only | gzip -c > "$BACKUPDIR/postgresql-globals.sql.gz"

# Geoserver
tar -zcpf $BACKUPDIR/geoserver.tar.gz /etc/geoserver /etc/geoserver/data/gwc/geowebcache.xml

# Qgis
tar -zcpf $BACKUPDIR/qgis.tar.gz /usr/lib/cgi-bin

# Www
tar -zcpf $BACKUPDIR/www.tar.gz /var/www

# Varnish configs
tar -zcpf $BACKUPDIR/varnish.tar.gz /etc/varnish /etc/default/varnish*

# Postgresql configs
tar -zcpf $BACKUPDIR/postgresql.tar.gz /etc/postgresql/9.5/main

# Pgpool configs
tar -zcpf $BACKUPDIR/pgpool.tar.gz /usr/local/etc

# System configs
tar -zcpf $BACKUPDIR/system.tar.gz /etc/rc.local /etc/fstab /etc/sysctl.conf /etc/hosts

# Php configs
tar -zcpf $BACKUPDIR/php.tar.gz /etc/php/7.0/fpm

# Apache configs
tar -zcpf $BACKUPDIR/apache.tar.gz /etc/apache2

# Samba configs
tar -zcpf $BACKUPDIR/samba.tar.gz /etc/samba

# Wiki
/usr/sbin/service mysql restart
mysqldump --databases --user=wikiuser --password=iiT6aX40IrWGIX4m --add-drop-database wikidb | gzip > $BACKUPDIR/wikidb.sql.gz

# Mapfish configs
tar -zcpf $BACKUPDIR/print-servlet.tar.gz /var/lib/tomcat7/webapps/print-servlet/*.yaml

# Scripts and manually installed executables
tar -zcpf $BACKUPDIR/usr-local-bin.tar.gz /usr/local/bin

# Root crontab
crontab -l > /root/crontablatest.txt
tar -zcpf $BACKUPDIR/crontab.tar.gz /root/crontablatest.txt /root/schemalagda_gnome-schedule/*.txt /root/schemalagda_gnome-schedule/*.sh

# Backup scripts
tar -zcpf $BACKUPDIR/backupscripts.tar.gz /mnt/sbkbackup/backup_scripts
