#!/bin/sh
# Weekday backup (five cycling backups)
set -e +a +m +s +i -f

local day="$(/usr/local/bin/date +%a)"
local backupdir="$VAR_BACKUP_DIR/weekdays/$day"
local IFS=$(echo -en "\n\b,")
local schemas=""
local tables=""
local dumpCmd=""
local blobs=""
local clean=""
local format=""
for database in $VAR_DATABASES
do
   eval "format=\$VAR_$database_format"
   if [ -z "$format" ]
   then
      format=$VAR_FORMAT
   fi
   dumpCmd="/usr/local/bin/pg_dump --host=$VAR_HOST --port=$VAR_PORT --username=$VAR_LINUX_USER --dbname=$database --format=$format"
   eval "clean=\$VAR_$database_clean"
   if [ "$clean" != "no" ]
   then
      if [ "$clean" == "yes" ] || [ "$VAR_CLEAN" == "yes" ]
      then
         dumpCmd="$dumpCmd --clean"
      fi
   fi
   
   dumpCmd="/usr/local/bin/pg_dump --host=$VAR_HOST --port=$VAR_PORT --username=$VAR_LINUX_USER --dbname=$database --format=$format"


   dumpCmd="$dumpCmd  
   if [ "$VAR_FORMAT" == "directory" ]
   then
      dumpCmd="$dumpCmd --jobs=$VAR_JOBS"
   fi
   eval "clean=\$VAR_$database_cleanobjects"
   if [ "$clean" == "yes" ]
   then
      dumbCmd="$dumpCmd --clean"
   fi
   eval "schemas=\$VAR_$database_schemas"
   if [ -n "$schemas" ]
   then
      for schema in $schemas
      do
         eval "blobs=\$VAR_$database_$schema_dumpblobs"
         if [ "$blobs" != "no" ]
         then
            dumpCmd="$dumpCmd --blobs"
         fi
         eval "tables=\$VAR_$database_$schema_tables"
         if [ -n "$tables" ]
         then
            for table in $tables
      do
         /usr/local/bin/pg_dump -U $VAR_LINUX_USER -p $VAR_PORT -N 'public' -N '*_' --exclude-table-data='*.*_' -Z 9 $i > "$BACKUPDIR/$i.sql.gz"
   pg_dump -U postgres -p 5432 -c -t 'layer_styles' -Z 9 $i > "$BACKUPDIR/$i-layer_styles.sql.gz"
done
pg_dumpall -h localhost -p 5432 -U postgres -w -v --globals-only | gzip -c > "$BACKUPDIR/postgresql-globals.sql.gz"

# Geoserver
tar -zcpf $BACKUPDIR/geoserver.tar.gz /etc/geoserver /etc/geoserver/data/gwc/geowebcache.xml

# Qgis
tar -zcpf $BACKUPDIR/qgis.tar.gz /usr/lib/cgi-bin

# Www
tar -zcpf $BACKUPDIR/www.tar.gz /var/www

# Varnish configs
tar -zcpf $BACKUPDIR/varnish.tar.gz /etc/varnish /etc/default/varnish*

# Postgresql configs
tar -zcpf $BACKUPDIR/postgresql.tar.gz /etc/postgresql/9.5/main

# Pgpool configs
tar -zcpf $BACKUPDIR/pgpool.tar.gz /usr/local/etc

# System configs
tar -zcpf $BACKUPDIR/system.tar.gz /etc/rc.local /etc/fstab /etc/sysctl.conf /etc/hosts

# Php configs
tar -zcpf $BACKUPDIR/php.tar.gz /etc/php/7.0/fpm

# Apache configs
tar -zcpf $BACKUPDIR/apache.tar.gz /etc/apache2

# Samba configs
tar -zcpf $BACKUPDIR/samba.tar.gz /etc/samba

# Wiki
/usr/sbin/service mysql restart
mysqldump --databases --user=wikiuser --password=iiT6aX40IrWGIX4m --add-drop-database wikidb | gzip > $BACKUPDIR/wikidb.sql.gz

# Mapfish configs
tar -zcpf $BACKUPDIR/print-servlet.tar.gz /var/lib/tomcat7/webapps/print-servlet/*.yaml

# Scripts and manually installed executables
tar -zcpf $BACKUPDIR/usr-local-bin.tar.gz /usr/local/bin

# Root crontab
crontab -l > /root/crontablatest.txt
tar -zcpf $BACKUPDIR/crontab.tar.gz /root/crontablatest.txt /root/schemalagda_gnome-schedule/*.txt /root/schemalagda_gnome-schedule/*.sh

# Backup scripts
tar -zcpf $BACKUPDIR/backupscripts.tar.gz /mnt/sbkbackup/backup_scripts
