#!/bin/sh
# Weekday backup (five cycling backups)

set -e +a +m +s +i
for function in /backup_scripts/functions/*
do
   if [ -f "$function" ]
   then
      . "$function"
   fi
done
set -f
day="$(/bin/date +%a)"
backupDir="$VAR_BACKUP_DIR/weekdays/$day"
backupDbToDir "$backupDir"
